// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package zmx

import (
	"github.com/joshmedeski/sesh/v2/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockZmx creates a new instance of MockZmx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockZmx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockZmx {
	mock := &MockZmx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockZmx is an autogenerated mock type for the Zmx type
type MockZmx struct {
	mock.Mock
}

type MockZmx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockZmx) EXPECT() *MockZmx_Expecter {
	return &MockZmx_Expecter{mock: &_m.Mock}
}

// Attach provides a mock function for the type MockZmx
func (_mock *MockZmx) Attach(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockZmx_Attach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attach'
type MockZmx_Attach_Call struct {
	*mock.Call
}

// Attach is a helper method to define mock.On call
//   - name string
func (_e *MockZmx_Expecter) Attach(name interface{}) *MockZmx_Attach_Call {
	return &MockZmx_Attach_Call{Call: _e.mock.On("Attach", name)}
}

func (_c *MockZmx_Attach_Call) Run(run func(name string)) *MockZmx_Attach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockZmx_Attach_Call) Return(s string, err error) *MockZmx_Attach_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockZmx_Attach_Call) RunAndReturn(run func(name string) (string, error)) *MockZmx_Attach_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentSessionName provides a mock function for the type MockZmx
func (_mock *MockZmx) CurrentSessionName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentSessionName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockZmx_CurrentSessionName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentSessionName'
type MockZmx_CurrentSessionName_Call struct {
	*mock.Call
}

// CurrentSessionName is a helper method to define mock.On call
func (_e *MockZmx_Expecter) CurrentSessionName() *MockZmx_CurrentSessionName_Call {
	return &MockZmx_CurrentSessionName_Call{Call: _e.mock.On("CurrentSessionName")}
}

func (_c *MockZmx_CurrentSessionName_Call) Run(run func()) *MockZmx_CurrentSessionName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockZmx_CurrentSessionName_Call) Return(s string) *MockZmx_CurrentSessionName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockZmx_CurrentSessionName_Call) RunAndReturn(run func() string) *MockZmx_CurrentSessionName_Call {
	_c.Call.Return(run)
	return _c
}

// IsAttached provides a mock function for the type MockZmx
func (_mock *MockZmx) IsAttached() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAttached")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockZmx_IsAttached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAttached'
type MockZmx_IsAttached_Call struct {
	*mock.Call
}

// IsAttached is a helper method to define mock.On call
func (_e *MockZmx_Expecter) IsAttached() *MockZmx_IsAttached_Call {
	return &MockZmx_IsAttached_Call{Call: _e.mock.On("IsAttached")}
}

func (_c *MockZmx_IsAttached_Call) Run(run func()) *MockZmx_IsAttached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockZmx_IsAttached_Call) Return(b bool) *MockZmx_IsAttached_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockZmx_IsAttached_Call) RunAndReturn(run func() bool) *MockZmx_IsAttached_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function for the type MockZmx
func (_mock *MockZmx) ListSessions() ([]*model.ZmxSession, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []*model.ZmxSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*model.ZmxSession, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*model.ZmxSession); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ZmxSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockZmx_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockZmx_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
func (_e *MockZmx_Expecter) ListSessions() *MockZmx_ListSessions_Call {
	return &MockZmx_ListSessions_Call{Call: _e.mock.On("ListSessions")}
}

func (_c *MockZmx_ListSessions_Call) Run(run func()) *MockZmx_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockZmx_ListSessions_Call) Return(zmxSessions []*model.ZmxSession, err error) *MockZmx_ListSessions_Call {
	_c.Call.Return(zmxSessions, err)
	return _c
}

func (_c *MockZmx_ListSessions_Call) RunAndReturn(run func() ([]*model.ZmxSession, error)) *MockZmx_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockZmx
func (_mock *MockZmx) Run(name string, args ...string) (string, error) {
	// string
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) (string, error)); ok {
		return returnFunc(name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...string) string); ok {
		r0 = returnFunc(name, args...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = returnFunc(name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockZmx_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockZmx_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - name string
//   - args ...string
func (_e *MockZmx_Expecter) Run(name interface{}, args ...interface{}) *MockZmx_Run_Call {
	return &MockZmx_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{name}, args...)...)}
}

func (_c *MockZmx_Run_Call) Run(run func(name string, args ...string)) *MockZmx_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockZmx_Run_Call) Return(s string, err error) *MockZmx_Run_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockZmx_Run_Call) RunAndReturn(run func(name string, args ...string) (string, error)) *MockZmx_Run_Call {
	_c.Call.Return(run)
	return _c
}
